#!/usr/bin/env node
// update-docs.js — called by Claude Code PostToolUse hook
// Usage: node update-docs.js <changed-file-path>
// - If changed file is api/**/*.js  → regenerates docs/api-report.md
// - If changed file is pages/*.html → updates/creates corresponding docs/dashboard-*.md

const fs   = require('fs');
const path = require('path');

const ROOT     = path.resolve(__dirname, '..');
const API_DIR  = path.join(ROOT, 'api');
const PAGES_DIR = path.join(ROOT, 'pages');
const DOCS_DIR  = path.join(ROOT, 'docs');
const TODAY    = new Date().toISOString().slice(0, 10);

const changedFile = process.argv[2] || '';

// ─── Helpers ────────────────────────────────────────────────────────────────

function readLines(filePath, n = 15) {
  try {
    return fs.readFileSync(filePath, 'utf8').split('\n').slice(0, n).join('\n');
  } catch { return ''; }
}

function readFull(filePath) {
  try { return fs.readFileSync(filePath, 'utf8'); } catch { return ''; }
}

function walkDir(dir, ext) {
  const results = [];
  if (!fs.existsSync(dir)) return results;
  for (const f of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, f.name);
    if (f.isDirectory()) results.push(...walkDir(full, ext));
    else if (f.name.endsWith(ext)) results.push(full);
  }
  return results;
}

// Extract comment lines from top of JS file
function extractJsHeader(filePath) {
  const lines = readFull(filePath).split('\n');
  const comments = [];
  for (const line of lines) {
    const t = line.trim();
    if (t.startsWith('//') || t === '') comments.push(t);
    else break;
  }
  return comments.filter(l => l.startsWith('//')).map(l => l.replace(/^\/\/\s?/, '')).join('\n');
}

// Extract text content of a regex match group from HTML
function htmlExtract(html, pattern, fallback = '') {
  const m = html.match(pattern);
  return m ? m[1].trim() : fallback;
}

// ─── 1. Update api-report.md ─────────────────────────────────────────────────

function updateApiReport() {
  const apiFiles = walkDir(API_DIR, '.js');
  if (apiFiles.length === 0) { console.log('No API files found.'); return; }

  const DOC_MAP = {
    'jackshan': 'pages/jakshan.html',
    'theekshy': 'pages/theekshy.html',
    'thivajini': 'pages/thivajini.html',
    'sajeepan': 'pages/sajeepan.html',
    'sonya':    'pages/sonya.html',
    'hetheesha': 'pages/hetheesha.html',
    'organic-revenue': 'pages/organic-revenue.html',
    'seo':      'pages/seo.html',
    'germany':  'Germany dashboard',
  };

  const DATA_SOURCES = new Set();
  let sections = '';

  for (const f of apiFiles) {
    const rel     = path.relative(ROOT, f).replace(/\\/g, '/');
    const header  = extractJsHeader(f);
    const content = readFull(f);

    // Extract types from comments like "?type=req1"
    const types = [...header.matchAll(/\?type=(\S+)/g)].map(m => m[1]);
    // Extract schema references
    const schemas = [...new Set([...content.matchAll(/(\w+_?\w+)\.(orders|page|query_page|campaign_performance|product_performance|shopify_listings|shopify_listing_meta|order_item_info|physical_product_stock|merchant_products|organic_landing_page_revenue|gsc_web_page)/g)].map(m => m[1]))];
    schemas.forEach(s => DATA_SOURCES.add(s));

    // Detect Shopify GraphQL usage
    const usesShopify = content.includes('myshopify.com') || content.includes('graphql');

    // Derive endpoint
    const endpoint = '/api/' + rel.replace('api/', '').replace('.js', '');

    // Find which page uses it
    const dirPart = path.dirname(rel).replace('api/', '');
    const usedIn  = Object.entries(DOC_MAP).find(([k]) => rel.includes(k))?.[1] || 'Shared';

    sections += `\n### \`${rel}\`\n`;
    sections += `- **Endpoint:** \`${endpoint}\`\n`;
    sections += `- **Used In:** ${usedIn}\n`;
    if (types.length) sections += `- **Types:** ${types.map(t => `\`?type=${t}\``).join(', ')}\n`;
    if (schemas.length) sections += `- **DB Schemas:** ${schemas.join(', ')}\n`;
    if (usesShopify) sections += `- **Also uses:** Shopify Admin GraphQL (live)\n`;
    sections += `- **Header notes:**\n\`\`\`\n${header || '(no header comments)'}\n\`\`\`\n`;
  }

  const dsTable = [...DATA_SOURCES].map(s => `| \`${s}\` | See individual API entries above |`).join('\n');

  const report = `# Staff Requirements — API Report

**Total API Files:** ${apiFiles.length}
**Location:** \`Staff-requirements-02/api/\`
**Generated:** ${TODAY}
**Auto-generated by:** \`scripts/update-docs.js\`

---

## API Files
${sections}

---

## Data Source Summary

| Schema | Notes |
|--------|-------|
${dsTable}
| **Shopify Admin GraphQL (live)** | hetheesha req1/req2, thivajini req1, seo |
`;

  fs.writeFileSync(path.join(DOCS_DIR, 'api-report.md'), report, 'utf8');
  console.log(`[update-docs] api-report.md updated (${apiFiles.length} files)`);
}

// ─── 2. Update dashboard-*.md ─────────────────────────────────────────────────

const PAGE_TO_DOC = {
  'jakshan':               'dashboard-jakshan.md',
  'theekshy':              'dashboard-theekshy.md',
  'thivajini':             'dashboard-thivajini.md',
  'sajeepan':              'dashboard-sajeepan.md',
  'sonya':                 'dashboard-sonya.md',
  'hetheesha':             'dashboard-hetheesha.md',
  'organic-revenue':       'dashboard-organic-revenue.md',
  'organic-revenue-guide': 'dashboard-organic-revenue-guide.md',
  'seo-docs':              'dashboard-seo-docs.md',
  'seo':                   'seo-intelligence-dashboard.md',
};

function updateDashboardDoc(htmlFile) {
  const basename = path.basename(htmlFile, '.html');
  const docFile  = PAGE_TO_DOC[basename];
  if (!docFile) { console.log(`[update-docs] No doc mapping for ${basename}.html — skipping`); return; }

  const html  = readFull(htmlFile);
  const title = htmlExtract(html, /<title>([^<]+)<\/title>/, basename);

  // Strip <style> blocks before parsing so CSS class names don't match
  const htmlNoStyle = html.replace(/<style[\s\S]*?<\/style>/gi, '');

  // Extract tab/section buttons — match full button inner HTML then strip tags
  const navMatches = [...htmlNoStyle.matchAll(/<(?:button|a)[^>]+nav-btn[^>]*>([\s\S]*?)<\/(?:button|a)>/g)];
  const tabs = navMatches.map(m => {
    // Strip inner HTML tags, collapse whitespace
    return m[1].replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').replace(/&amp;/g, '&').trim();
  }).filter(t => t && t.length > 1 && t.length < 100 && !t.includes('{'));

  // Extract sec-title elements (strip style blocks first)
  const secTitles = [...htmlNoStyle.matchAll(/class="[^"]*sec-title[^"]*">([^<]{2,80})<\/div>/g)].map(m => m[1].trim());

  // Extract fetch() calls
  const fetches = [...new Set([...htmlNoStyle.matchAll(/fetch\(['"`]([^'"`\n]+)['"`]/g)].map(m => m[1]))];

  // Extract API URL patterns
  const apiCalls = fetches.filter(f => f.startsWith('/api') || f.includes('api/'));

  const docPath = path.join(DOCS_DIR, docFile);
  const existing = readFull(docPath);

  // Update Last updated line if file exists, otherwise create fresh
  let updated;
  if (existing) {
    updated = existing.replace(/\*\*Last updated:\*\* \S+/, `**Last updated:** ${TODAY}`);
    // Append a change note if tabs/sections changed
    const tabSection = tabs.length
      ? `\n\n---\n\n> *Auto-synced ${TODAY} — Tabs/sections detected: ${tabs.slice(0,8).join(', ')}*`
      : '';
    // Only append if the note doesn't already exist for today
    if (!updated.includes(`Auto-synced ${TODAY}`) && tabSection) {
      updated = updated.replace(/\n>\s*\*Auto-synced[^\n]*\n?/g, '');
      updated += tabSection + '\n';
    }
  } else {
    // Create new doc
    const tabRows = tabs.slice(0,10).map((t, i) => `| ${i+1} | ${t} |`).join('\n');
    const secRows = secTitles.slice(0,8).map((s, i) => `| ${i+1} | ${s} |`).join('\n');
    const apiRows = apiCalls.map(a => `- \`${a}\``).join('\n');

    updated = `# ${title}

**File:** \`pages/${basename}.html\`
**Title:** ${title}
**Last updated:** ${TODAY}

---

## Purpose

*(Auto-generated — add description here)*

---

## Structure

${tabs.length ? `| # | Tab/Section |\n|---|---|\n${tabRows}` : secRows.length ? `| # | Section |\n|---|---|\n${secRows}` : '*(No tabs detected)*'}

---

## API Calls

${apiRows || '*(No fetch() calls detected)*'}

---

## Tables Used

*(Add DB table details here)*

---

## Key Logic

*(Add key logic notes here)*
`;
  }

  fs.writeFileSync(docPath, updated, 'utf8');
  console.log(`[update-docs] ${docFile} updated`);
}

// ─── Main ────────────────────────────────────────────────────────────────────

const normalised = changedFile.replace(/\\/g, '/');

if (normalised.includes('Staff-requirements-02/api/') && normalised.endsWith('.js')) {
  updateApiReport();
} else if (normalised.includes('Staff-requirements-02/pages/') && normalised.endsWith('.html')) {
  updateDashboardDoc(changedFile);
} else {
  // Not a file we care about — exit 0, never block
  process.exit(0);
}
